---
name: emacs-tap-mode
abstract: Emacs syntax highlighting for TAP (Test Anything Protocol)
version: 0.02
author:
  - Steffen Schwigon <ss5@renormalist.net>
license: perl
distribution_type: script
resources:
  license: http://dev.perl.org/licenses/
  homepage: http://renormalist.net/cgi-bin/twiki/view/Renormalist/TapMode
meta-spec:
  version: 1.3
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Steffen Schwigon
provides:
  tap-mode:
    file: tap-mode.el
    abstract: Emacs syntax highlighting for TAP (Test Anything Protocol)
    version: 0.02
